# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nic's Blog
author:
  name: "Nic Finn"
  twitter: neodymiumphish
  bio-url: "https://neodymiumphi.sh"
description: >- # this means to ignore newlines until "baseurl:"
  Always a Work in Progress!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neodymiumphi.sh" # the base hostname & protocol for your site, e.g. http://example.com
root: /
permalink: /:title/
external-url-indicator: " »"
google_analytics_ga4: G-PYTR3VNVSZ
# Build settings
theme: henry-jekyll
markdown: kramdown
highlighter: rouge
encoding: utf-8

plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Front matter defaults
defaults:
- scope:
    path: "" # an empty string here means all files in the project
    type: "posts" # pages, posts, drafts are valid
  values:
    layout: "post"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - _sass/
 - .jekyll-cache/
 - Gemfile
 - Gemfile.lock
 - _includes
 - .git/
 - .ruby-version
 - .henry-jekyll.gemspec
 - .obsidian
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
