# Setup
title:               Neodymium Phish
tagline:             'Random CTI Thoughts'
description:         'Personal blog, thoughts and opinions are my own. Operated by <a href="https://x.com/NeodymiumPhish" target="_blank">@NeodymiumPhish</a>'
url:                 https://neodymiumphi.sh
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nic Finn
  url:               https://x.com/NeodymiumPhish
  email:             nic@neodymiumphi.sh

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 
